library(openCyto)
library(projr)
library(class)
library(nnet)
library(cluster)
library(codetools)
library(rpart)
library(askpass)
library(backports)
library(base64enc)
library(bit)
library(bit64)
library(boot)
library(broom)
library(bslib)
library(cachem)
library(cffr)
library(checkmate)
library(clipr)
library(codemeta)
library(cowplot)
library(crul)
library(curl)
library(doParallel)
library(e1071)
library(ellipse)
library(evaluate)
library(fastmap)
library(fontawesome)
library(forcats)
library(foreach)
library(foreign)
library(Formula)
library(gdata)
library(gh)
library(gitcreds)
library(glmnet)
library(gridExtra)
library(gtools)
library(haven)
library(highr)
library(Hmisc)
library(hms)
library(htmlTable)
library(htmltools)
library(htmlwidgets)
library(httpcode)
library(httr)
library(httr2)
library(ini)
library(iterators)
library(jomo)
library(jquerylib)
library(jsonvalidate)
library(knitr)
library(later)
library(lme4)
library(lubridate)
library(memoise)
library(mice)
library(mime)
library(minqa)
library(mitml)
library(nloptr)
library(nnls)
library(numDeriv)
library(openssl)
library(ordinal)
library(osfr)
library(pan)
library(piggyback)
library(plotrix)
library(polynom)
library(prettyunits)
library(processx)
library(progress)
library(proxy)
library(ps)
library(purrr)
library(quarto)
library(rappdirs)
library(readr)
library(rmarkdown)
library(rstudioapi)
library(sass)
library(shape)
library(smacof)
library(stringi)
library(stringr)
library(survival)
library(sys)
library(tidyr)
library(timechange)
library(tinytex)
library(triebeard)
library(tzdb)
library(ucminf)
library(urltools)
library(V8)
library(viridis)
library(vroom)
library(weights)
library(wordcloud)
library(xfun)


renv_lockfile <- renv:::lockfile_read()

renv_pkg_non_bioc <- lapply(renv_lockfile$Packages, function(x) {
  if (grepl("bioc", tolower(x$Source))) {
    NULL
  } else {
    x$Package
  }
}) |>
  unlist() |>
  setdiff("renv")

for (x in renv_pkg_non_bioc) {
  if (!requireNamespace(x, quietly = TRUE)) {
    message("Installing ", x)
    try(renv::install(x, dependencies = TRUE, prompt = FALSE))
  }
}
renv_pkg_non_bioc_remaining <- setdiff(renv_pkg_non_bioc, installed.packages()[, "Package"])

pkg_dep_vec <- c("lme4", "Hmisc", "jomo", "htmlTable", "gridExtra", "crul")
renv::install(pkg_dep_vec, dependencies = TRUE, prompt = FALSE)


BiocManager::install("openCyto")
